"""empty message

Revision ID: d1ae94f54824
Revises: 9edd571b1587
Create Date: 2024-10-19 20:41:56.983294

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd1ae94f54824'
down_revision = '9edd571b1587'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('People',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('url', sa.String(length=450), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('url')
    )
    op.create_table('Planet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('climate', sa.String(length=150), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('edited_at', sa.DateTime(), nullable=False),
    sa.Column('diameter', sa.String(length=150), nullable=False),
    sa.Column('films', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('gravitiy', sa.String(length=150), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('orbital_period', sa.String(length=150), nullable=False),
    sa.Column('population', sa.String(length=150), nullable=False),
    sa.Column('residents', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('rotation_period', sa.String(length=150), nullable=False),
    sa.Column('surface_water', sa.String(length=150), nullable=False),
    sa.Column('terrain', sa.String(length=150), nullable=False),
    sa.Column('url', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('favorite',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('planet_id', sa.Integer(), nullable=True),
    sa.Column('people_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['people_id'], ['People.id'], ),
    sa.ForeignKeyConstraint(['planet_id'], ['Planets.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('User')
    op.drop_table('Favorite')
    with op.batch_alter_table('Person', schema=None) as batch_op:
        batch_op.add_column(sa.Column('films', sa.ARRAY(sa.String()), nullable=False))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('edited_at', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('species', sa.ARRAY(sa.String()), nullable=False))
        batch_op.add_column(sa.Column('starships', sa.ARRAY(sa.String()), nullable=False))
        batch_op.add_column(sa.Column('vehicles', sa.ARRAY(sa.String()), nullable=False))

    with op.batch_alter_table('Planets', schema=None) as batch_op:
        batch_op.alter_column('url',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.String(length=450),
               existing_nullable=False)
        batch_op.create_unique_constraint(None, ['url'])
        batch_op.create_unique_constraint(None, ['name'])
        batch_op.drop_column('terrain')
        batch_op.drop_column('population')
        batch_op.drop_column('climate')
        batch_op.drop_column('gravity')
        batch_op.drop_column('orbital_period')
        batch_op.drop_column('diameter')
        batch_op.drop_column('rotation_period')
        batch_op.drop_column('residents')
        batch_op.drop_column('surface_water')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Planets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('surface_water', sa.VARCHAR(length=150), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('residents', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('rotation_period', sa.VARCHAR(length=150), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('diameter', sa.VARCHAR(length=150), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('orbital_period', sa.VARCHAR(length=150), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('gravity', sa.VARCHAR(length=150), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('climate', sa.VARCHAR(length=150), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('population', sa.VARCHAR(length=150), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('terrain', sa.VARCHAR(length=150), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('url',
               existing_type=sa.String(length=450),
               type_=sa.VARCHAR(length=150),
               existing_nullable=False)

    with op.batch_alter_table('Person', schema=None) as batch_op:
        batch_op.drop_column('vehicles')
        batch_op.drop_column('starships')
        batch_op.drop_column('species')
        batch_op.drop_column('edited_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('films')

    op.create_table('Favorite',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Favorite_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('planet_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('people_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['people_id'], ['Person.id'], name='Favorite_people_id_fkey'),
    sa.ForeignKeyConstraint(['planet_id'], ['Planets.id'], name='Favorite_planet_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], name='Favorite_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='Favorite_pkey')
    )
    op.create_table('User',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"User_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='User_pkey'),
    sa.UniqueConstraint('email', name='User_email_key')
    )
    op.drop_table('favorite')
    op.drop_table('user')
    op.drop_table('Planet')
    op.drop_table('People')
    # ### end Alembic commands ###
